#!/bin/bash  -xue

mkdir -p .work
/usr/bin/rm -f .work/index.html

pushd  .work
wget  https://www.mercurial-scm.org/release/
popd

grep -E '>mercurial-[0-9.]+\.tar\.gz<'  .work/index.html  |  \
    sed -E 's/^.*a href="mercurial-([0-9.]+)\.tar\.gz">.*$/\1/'  \
    |  tee  VersionList.txt
